# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c15cff0ddaa76da12cf16fd1530c8f40"
name = "layyer"
handle = "layyer"
application_url = "https://orange-lakes-approach-dutch.trycloudflare.com"
embedded = true
app_type = "public"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://orange-lakes-approach-dutch.trycloudflare.com/auth/callback",
  "https://orange-lakes-approach-dutch.trycloudflare.com/auth/shopify/callback",
  "https://orange-lakes-approach-dutch.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
